### ISSUE TITLE
ESPHome 2023.9.1 - error "Platform missing. You must include one of the available platform key esp32, esp8266, rp2040, host"

### ISSUE THREAD

**Issue by MnM001** [libretiny-eu/libretiny#177]
I updated to ESPHome 2023.9.1.

![image](https://github.com/libretiny-eu/libretiny/assets/15014858/5264af69-3b80-4596-83db-c4fafeebc973)

It does mention that libretiny is natively supported now.
However get the error below:

![image](https://github.com/libretiny-eu/libretiny/assets/15014858/eb8cba1b-7f14-4e4b-a5ee-e96aaeb5026c)

LibreTiny ESPHome - no errors there

![image](https://github.com/libretiny-eu/libretiny/assets/15014858/25e29d17-c836-4eb0-844b-4db9026a47d5)

![image](https://github.com/libretiny-eu/libretiny/assets/15014858/3dc39c82-a7e9-4efc-a6a2-8d97ddcd81a0)

**Comment by Cossid** [comment]
Try removing
```
framework:
  version: dev
  ```

**Comment by MnM001** [comment]
Same error.
The error is one the bk72xx line.... 
Cleaning build files did not solve the issue:

![image](https://github.com/libretiny-eu/libretiny/assets/15014858/c9882505-bef2-48b0-8dc0-7b71f285f215)

**Comment by Cossid** [comment]
That's a different error.  You need to replace `ledc` with `libretiny_pwm` moving forward.

**Comment by MnM001** [comment]
And that worked :) - thanks.

Are any more changes like this? I don't think I saw anything documented for this.

**Comment by Cossid** [comment]
Nope, that is pretty much it.
