### ISSUE TITLE
Tuya WBR3

### ISSUE THREAD

**Issue by guestisp** [libretiny-eu/libretiny#186]
Guys, is the Tuya WBR3 chipset (i think it's a RTL8720CM) supported ? 
https://solution.tuya.com/hardware/detail/59006

I can see support for the RTL8720CM but in the Tuya devices list the WBR3 is not present.

**Comment by kuba2k2** [comment]
RTL8720, whether is CM or CF, is not supported yet. See #44 .

**Comment by guestisp** [comment]
So, why RTL8720CF is listed here as supported ? 
![image](https://github.com/libretiny-eu/libretiny/assets/3944655/4c2e9c8f-b916-47a7-bca0-4cc49041b446)

**Comment by kuba2k2** [comment]
Because a development version (generic chip) was added to test and fix support for it. The core features work, but many important things such as OTA are not supported. See [Feature Support](https://docs.libretiny.eu/docs/status/supported/#feature-support) - RTL8720C is listed there.

**Comment by guestisp** [comment]
Uhm, probably i' could work with that anyway. I just need to trigger a change on a GPIO. (it's the ilonda wifi fish feeder, tuya based, not sure which chipset anyway, i'll know better tomorrow. It could be and esp8266 or this RTL)
