### ISSUE TITLE
RTL8720 Ota update Error binary size

### ISSUE THREAD

**Issue by esnet146** [libretiny-eu/libretiny#236]
![image](https://github.com/libretiny-eu/libretiny/assets/64173457/eb09c1f4-c2f4-4007-8404-1d6d971a73b6)
Config:
```
rtl87xx:
  board: wbr3
  family: rtl8720c
  framework:
     version: 0.0.0
     source: https://github.com/libretiny-eu/libretiny.git#feature/realtek-update
```
OTA update does not work?

log dashboard:
HARDWARE: RTL8720CF 100MHz, 256KB RAM, 896KB Flash
 - framework-arduino-api @ 2022.8.24+sha.237b10a 
 - framework-realtek-ambz2 @ 0.0.0+v2022.11.17.sha.5f7b937 
 - library-flashdb @ 1.2.0+sha.d5c892f 
 - library-freertos @ 10.0.1+sha.752c89a 
 - library-freertos-port @ 2023.5.23+sha.a917d93 
 - library-lwip @ 2.1.3-ambz2+sha.929d2dd 
 - library-printf @ 6.1.0+sha.28a79bd 
 - library-uf2ota @ 5.0.0+sha.f955412 
PLATFORM VERSIONS:
 - libretiny @ 1.4.1+sha.d41d328
 - ltchiptool @ 4.10.1
CUSTOM OPTIONS:
 - fw_name = esphome
 - fw_version = 2023.12.5
Dependency Graph
|-- noise-c @ 0.1.4
RAM:   [          ]   5.0% (used 13033 bytes from 262144 bytes)
Flash: [======    ]  59.5% (used 546345 bytes from 917504 bytes)
========================= [SUCCESS] Took 13.96 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.22
INFO Uploading /data/build/wbr3-01/.pioenvs/wbr3-01/firmware.uf2 (1189376 bytes)
ERROR Error binary size: Unknown error from ESP

Log uart:
[D][ota:151]: Starting OTA Update from 192.168.1.2...
E [     46.712] OTA is not yet supported on this chip!

Ltchiptool 4.10.1 successfully flashes
![image](https://github.com/libretiny-eu/libretiny/assets/64173457/b8a50dd9-1532-4f94-b65c-2ad5d3c7aac0)

**Comment by kuba2k2** [comment]
The log says it clearly: OTA is not yet supported on this chip!
