### ISSUE TITLE
New Device USB Rechargeable LED Night Light Tuya WiFi Smart Motion Sensor

### ISSUE THREAD

**Issue by Liionboy** [libretiny-eu/libretiny#246]
Hello,

Anyone can help me to tell how i can control this new device via Esphome, what i do until now i can control LED as light and see PIR sensor and LUX sensor but don't work like on tuya App

https://vi.aliexpress.com/item/1005005671485856.html?spm=a2g0o.order_list.order_list_main.16.4e5f1c24BrcPTA&gatewayAdapt=glo2vnm

Code from ESPHome:

esphome:
  name: lumina-hol1

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_smart
  password: !secret wifi_smart_pass
  ap:

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime
  - platform: adc
    pin: P23
    id: lux_sensor
    name: "LUX Sensor"
    update_interval: '10s'
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
output:
  - platform: libretiny_pwm
    id: output_cold
    pin: P24
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: light_monochromatic
    name: Light
    output: output_cold

binary_sensor:
  - platform: gpio
    pin: 26
    name: "PIR Sensor"
    device_class: motion
    id: pir_sensor_light
    on_press:
      then:
        - component.update: lux_sensor

What i extracted with Beken Flasher:

Device configuration, as extracted from Tuya: 
- LED Cool (Channel 4) on P24
- PWM Frequency1000
- PIR Sensitivity 8
- PIR Frequency20000
- Control Pin (TODO) on P26
- PIR Low Duty16
- PIR High Duty7
- PIR Input 6
Device seems to be using CBU module, which is using BK7231N.
And the Tuya section starts, as usual, at 2023424

Chip is CBU so i am using libretiny tuya, i saw on the pcb a LN4506:

http://www.natlinear.com/uploadfiles/LNXT/LN4506_E.pdf

And PIR sensor is:

W216S Anti- WiFi Type PIR Sensor

I will let some picture with device:

![IMG_7215](https://github.com/libretiny-eu/libretiny/assets/87735636/7b086b3a-9c39-4625-948b-3c6e804d0b9b)

Tuya APP:

![IMG_7216](https://github.com/libretiny-eu/libretiny/assets/87735636/deb96603-11ef-47cd-9460-cd10636e9e1b)
![IMG_7217](https://github.com/libretiny-eu/libretiny/assets/87735636/52d3c942-9490-48d8-8db7-2d59401e0c4c)

![IMG_7219](https://github.com/libretiny-eu/libretiny/assets/87735636/61dfe9f8-aa22-44ea-9a33-e98563b773cc)

Thanks

**Comment by Cossid** [comment]
This isn't really a topic for LibreTiny, this is a general ESPHome component configuration question.  It sounds like you have the basics down, including having all the relevant GPIO, but LibreTiny is just a platform, it's goal is to make ESPHome functional, not specific device configurations.  It will guide as best it can, but many things are beyond that scope.

I'd suggest you check out the official ESPHome discord for advice on how to tweak configurations of ESPHome components.  

Keep in mind, ESPHome may not fully support all functionality that the OEM firmware had.  Your alternate option would be to return to the OEM firmware (and possibly run it in cut mode if it is vulnerable).
