### ISSUE TITLE
RTL87xx chips don't support CHANGE interrupts

### ISSUE THREAD

**Issue by RF197** [libretiny-eu/libretiny#255]
RTL87xx chips don't (formally) support pin change interrupts. However, libraries like pulse_counter (which is used for energy monitoring in the hwl8012 library amongst others) uses it exclusively.

Would it be possible to attach a RISING and FALLING edge interrupt to the same ISR callback? That way these libraries could be supported by these chips...

**Comment by flohav** [comment]
Is it related to #155 ?

**Comment by RF197** [comment]
Oops, missed that one. Looks like there's even a workaround.

Thanks!
