### ISSUE TITLE
BK7231N : Save user data

### ISSUE THREAD

**Issue by TuanAIoT** [libretiny-eu/libretiny#256]
Hello everyone, I want to ask if there is a way to save user data:
Using an ESP32-like EEPROM library: not supported
Using library "Preferences.h": undefined
Using library "lt_flash.h" can be written and erased multiple times. Should I use this library to save wifi user information and wifi password?

**Comment by TuanAIoT** [comment]
![1](https://github.com/libretiny-eu/libretiny/assets/127066596/d44d01b8-013d-4cc9-a173-03df078a75d1)

**Comment by kuba2k2** [comment]
See #90.
