### ISSUE TITLE
BK7231N : The compiled Firmware file size exceeds the flash memory

### ISSUE THREAD

**Issue by TuanAIoT** [libretiny-eu/libretiny#268]
Chip : BK7231N
Module : CBU

Flash memory is 2MB, however when I compile the program it exceeds 2048kb,
despite only using 66% of memory (used 715616 bytes from 1083136 bytes)
![image](https://github.com/libretiny-eu/libretiny/assets/127066596/d7ac2f84-935c-4e50-9b28-adc9a0cf4041)
![image](https://github.com/libretiny-eu/libretiny/assets/127066596/55eb58f6-26a8-40b3-adf3-6240cfc2c080)

**Comment by Cossid** [comment]
That is completely normal, uf2 is a wrapping format with extra information about partitions, writing instructions, and validations.  The file is streamed and processed, and only the appropriate bits will be written as determined by the information streamed and processed.  You must use LTChipTool (or the OTA process which also implements uf2 depending on platform), and it will be handled correctly.

**Comment by TuanAIoT** [comment]
@Cossid ,
Exceeding the size of 2048KB causes an error when writing the firmware.bin file to the BK7231N chip
![image](https://github.com/libretiny-eu/libretiny/assets/127066596/63d15711-c50d-44ef-9921-947d00280313)

**Comment by kuba2k2** [comment]
Firmware.bin is exactly the same UF2 file. It's named this way so that people used to ESP platforms choose this file for flashing.

As Cossid said, it only works with LibreTiny flashing tools, which understand this file format. OpenBeken's flasher tool only understands raw binaries, so it will not be able to write UF2 files.

**Comment by TuanAIoT** [comment]
yes, thank you everyone, The problem has been resolved
