### ISSUE TITLE
Address WebServer

### ISSUE THREAD

**Issue by Mit4el** [libretiny-eu/libretiny#287]
if I use the WebServer HTTP(80), that is, without an address, then when HTTP.begin() is called, the server starts at 0.0.0.0:80. I use the standard web server from libretiny, not async from EspHome

**Comment by kuba2k2** [comment]
And what's the issue? 0.0.0.0 obviously means "any address", that is, you can connect to it on any IP address the device has (for example, both WiFi station and AP).

**Comment by Mit4el** [comment]
That's right, I was wrong. Sorry, it just doesn't open the web, and for some reason I immediately thought of the wrong address.
